trigger:
- main  # Replace with your desired branch if needed

pool:
  name: Default  # Use the default agent pool, or specify the one where your agent is installed

steps:
# Step 1: Run a simple shell command to verify agent is working
- script: echo "Hello, Azure DevOps! The agent is working."
  displayName: 'Test Agent Connection'

# Step 2: Check the system info to ensure the agent has necessary resources
- script: |
    echo "System Information:"
    uname -a
    df -h
    free -h
  displayName: 'Check System Info'
